### ISSUE TITLE
🍿[Epic] Provide an option to store encrypted seed when user installs app

### ISSUE THREAD

**Issue by kcw-grunt** [litecoin-foundation/litewallet-android#114]
## Overview
It's 2023 and users still fail to store their seed written on a piece of paper or in a safe.  And Litewallet still gets blamed. Enough!
When the user installs Litewallet, we should also give the user the option to store an encrypted copy in their gmail data files

### Why?
**Is your request related to a problem? Or, do you have an idea to improve the app? Please describe.**
 
This provides another layer of protection for users that fail  to follow our directions.

### What?
**Describe the solution you'd like**

This feature should both be added and the path of users ignoring the confirming the seed should be removed.  Users should not be able to progress further until the seed is confirmed.

### Definition of Done
- [ ] 🦺[Tech debt] Remove the options to save the seed. Block user until they confirm the seed.
- [ ] 🥳 [Feature] Add integration for saving to the iCloud connection 
- [ ] 🥳[Feature] Allow user ability to add storing encrypted seed if they initially reject (in settings)

## UI Changes

|**Before**|**After**|
|----------|---------|
|||
