### ISSUE TITLE
🦟[Bugfix] Crashlytics: libc.so Spike 

### ISSUE THREAD

**Issue by kcw-grunt** [litecoin-foundation/litewallet-android#259]
## Description

There a  long list of crashes associated with this libc.so.  This is likely due to the `loafwallet-core` dependency (which will be deprecated soon)

Meanwhile we need to address these crashes and identify the source

Address the related issues:

- [ ] 🦟[Bug Report] v2.9.0: Crashlytics: libc.so #151
- [ ] 🦟[Bug Report] Crashlytics: lib.c unknown #127 
- [ ] 🦟[Bug Report] Crashed v2.90-v2.12.X:[libc.so] #257
